Set priorityClassName to prometheus for fluentd daemonset
giantswarm/fluent-logshipping-app pull request #178
Opened 2024-06-04 10:10 UTC by TheoBrigitte

Towards: https://github.com/giantswarm/giantswarm/issues/30815

Set priorityClassName to prometheus for fluentd daemonset to fix scheduling issues.

I also removed the NoSchedule node taint toleration, as I felt this is wrong for fluentbit to be scheduled on such nodes.

2024-06-04 10:34 UTC, QuantumEnigmaa approved these changes
I'm fine with this but I still think that we should eventually have a dedicated priorityClass

2024-06-04 11:32 UTC, QuentinBisson requested changes
I'm not fine with this for multiple reasons:
1. Customers deploy this app in their WCs where this priority class does not exist
2. It should not have the same priority as prometheus because then which one is more important?

2024-06-04 11:33 UTC, TheoBrigitte commented
> I'm not fine with this

Can you explain why and/or suggest something ?

2024-06-04 11:33 UTC, QuentinBisson commented
Yes I can and I did, I wanted to block the merge first :D

2024-06-04 11:34 UTC, QuentinBisson commented
I'm bringing the priority class topic to @giantswarm/sig-architecture for this reason actually

2024-06-04 11:38 UTC, QuentinBisson commented
So the main idea is that we need our own priority class but I'd like to have an agreement in sig-arch on what values we can use accross the company

2024-06-12 08:59 UTC, QuentinBisson commented
Closing in favor of https://github.com/giantswarm/fluent-logshipping-app/pull/180

2024-06-12 08:59 UTC, closed without merging